# Generated by Django 4.1.4 on 2023-05-23 10:04

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0002_subscription"),
    ]

    operations = [
        migrations.AddField(
            model_name="subscription",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
    ]
