# Generated by Django 4.1.4 on 2023-06-07 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0005_subscription_subscriber_name_alter_subscription_date"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="subscription",
            name="subscriber_name",
        ),
        migrations.AlterField(
            model_name="subscription",
            name="date",
            field=models.DateField(),
        ),
    ]
