# Generated by Django 4.1.4 on 2023-06-07 13:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0008_alter_subscription_subscriber_name"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="subscription",
            name="subscriber_name",
        ),
    ]
