# Generated by Django 4.1.4 on 2023-06-07 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0009_remove_subscription_subscriber_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="subscription",
            name="subscriber_name",
            field=models.CharField(default="None", max_length=40),
        ),
    ]
