# Generated by Django 4.1.4 on 2023-06-12 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0010_subscription_subscriber_name"),
    ]

    operations = [
        migrations.CreateModel(
            name="Donation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                ("amt", models.IntegerField()),
                ("remarks", models.CharField(max_length=30, null=True)),
                ("is_subscriber", models.BooleanField(default=False)),
                ("donor_name", models.CharField(max_length=30)),
                ("donor_phone", models.CharField(max_length=10, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
