# Generated by Django 4.1.4 on 2023-06-13 08:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0011_donation"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="donation",
            name="is_subscriber",
        ),
    ]
